baseURL = "https://blog.kalinkov.com/"
languageCode = "en-us"
title = "Dimitar Kalinkov - Welcome to my world!"
theme = "cactus"
enableEmoji = true
disqusShortname = "blogkalinkov"
paginate = 10

[params]
	name = "Dimitar Kalinkov"
	description = "Describe your website"
	bio = "Welcome to my world!"
	# Enter optionally your twitter account
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""

	# Sharing options and author information in posts
	aboutAuthor = "I'm an blogger."
	tweet = " "
	share = " "
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    github   = "https://www.github.com/dkalinkov/"
    instagram = "https://www.instagram.com/dimkalinkov/"